SENSORILIB_DIR = ./sensori
SENSORILIB_SRCS = $(SENSORILIB_DIR)/mic.c $(SENSORILIB_DIR)/MEMS.c $(SENSORILIB_DIR)/prox.c
SENSORILIB_INCS = $(SENSORILIB_DIR)

ALLCSRC += $(SENSORILIB_SRCS)
ALLINC += $(SENSORILIB_INCS)